name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Find and Compile LaTeX Files
      run: |
        # Obter uma lista de diretórios modificados no commit
        CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/')

        if [ -z "$CHANGED_DIRS" ]; then
          echo "No directories changed!"
          exit 0
        fi

        # Procurar arquivos .tex dentro dos diretórios alterados
        TEX_FILES=$(find $CHANGED_DIRS -type f -name "*.tex")

