name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Find and Compile LaTeX File
      run: |
        TEX_FILE=$(find . -maxdepth 1 -name "*.tex" | head -n 1)
        if [ -z "$TEX_FILE" ]; then
          echo "No .tex file found!"
          exit 1
        fi
        BASENAME=$(basename "$TEX_FILE" .tex)
        pdflatex -interaction=nonstopmode -halt-on-error "$TEX_FILE"
        mkdir -p output
        mv "${BASENAME}.pdf" output/

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: PDF-Document
        path: output/

